# Generated by Django 3.1.1 on 2021-01-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='Demo_Link',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
