# Generated by Django 3.1.1 on 2021-01-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tip_Service_Level', models.CharField(choices=[('Great', 'Great'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor'), ('Miserable', 'Miserable'), ('Never Again', 'Never Again')], max_length=255)),
                ('Tip_Percent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Percentages',
                'ordering': ['-Tip_Percent'],
            },
        ),
    ]
