# Generated by Django 3.1.1 on 2021-02-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentage',
            name='Tip_Service_Description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
